source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'qmos_Example', :exclusive => true do
  pod 'qmos', :path => '../'
end

target 'qmos_Tests', :exclusive => true do
  pod 'qmos', :path => '../'

  
end
